# Generated by Django 3.2.5 on 2021-08-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_muro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(),
        ),
    ]
