# Generated by Django 3.2.5 on 2021-08-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_muro', '0002_auto_20210831_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(max_length=255),
        ),
    ]
